@startuml
sprite $AzureActiveDirectory [70x70/4] {
______________________________________________________________________
________________________________ym05n_________________________________
_____________________________ym0000LL5ny______________________________
___________________________ym000000LLLLL5ny___________________________
________________________ym000000000LLLLLLLL5y_________________________
______________________ym00000000000LLLLLLLLLL5ny______________________
___________________ym00000000000000LLLLLLLLLLLLL5r____________________
_________________ym0000000000000000LLLLLLLLLLLLLLLLny_________________
______________ym0000000000000000000LLLLLLLLLLLLLLLLLL5ry______________
____________y0000000000000000000000LLLLLLLLLLLLLLLLLLLLLrz____________
_________ym000000000000000000000000LLLLLLLLLLLLLLLLLLLLLLLLrz_________
_______y000000000000000000000000000LLLLLLLLLLLLLLLLLLLLLLLLLL5z_______
______30000000000000000000000000000LLLLLLLLLLLLLLLLLLLLLLLLLLLKN______
__m0mmyy_F3300000000000000000000000LLLLLLLLLLLLLLLLLLLLLLLNVV_zrrLLrz_
m00000000mmy__F33000000000000000000LLLLLLLLLLLLLLLLLLNNV_zzrLLLLLLLLLr
_F330000000000mmy_FF300000000000000LLLLLLLLLLLLLNNVFzzr5LLLLLLLLLLNNV_
_____FF300000000000myy_F33000000000LLLLLLLLLNVV_zrrLLLLLLLLLLNNVF_____
__________FF30000000000mmyyFF300000LLLLNJV_zzrLLLLLLLLLLLNVV__________
_______________F330000000000mmy_FF3NV_zzrLLLLLLLLLLLNJV_______________
___________________FF330000000000myrrLLLLLLLLLLNNV____________________
________________________F3300000000LLLLLLLLNVV________________________
_____________________________F33000LLLNVV_____________________________
_________________________________FFV__________________________________
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
}

@enduml
