@startuml
sprite $vmware [64x64/4] {
________________________________________________________________
___________yzpttttppppppppppppppppppppppppppppttttpzy___________
________zpDrqLLHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHLLqrDpz________
_____ytDrL5LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL5LrDty_____
____nFvL5LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL5LvFn____
____4_L1LLLLLLLLKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKLLLLLLLL1L_4____
____0_LLLLLLLLG0555LLLLLLLLLLLLLLLLLLLLLLLLLL5551GLLLLLLLL_0____
____0_LLLLLLLL0LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL0LLLLLLLL_0____
____0_LLLLLLLL0LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL0LLLLLLLL_0____
____0_LLLLLLLL0LLLLLLLLLLLLKKGGGGGGKKLLLLLLLLLLLL0LLLLLLLL_0____
____0_LLLLLLLL0LLLLLLLLLG0000000000000GKLLLLLLLLL0LLLLLLLL_0____
____0_LLLLLLLL0LLLLLLLK000000000000000000KKKLLLLL0LLLLLLLL_0____
____0_LLLLLLLL0LLLKKGG00000000000000000000000GKLL0LLLLLLLL_0____
____0_LLLLLLLL1GL111111111111111111111111111112LK1LLLLLLLL_0____
____0_LLLLLLLLL562IIIIIIIIIIIIIIIIIIIIIIIIIIII265LLLLLLLLL_0____
____0_LLLLLLLLLLLLLLLLLLLLKaaaaaaaaaaKLLLLLLLLLLLLLLLLLLLL_0____
____J_MLLLLLLLLLLLLLLLLLLG000000000000GLLLLLLLLLLLLLLLLLLM_J____
_____JzRLLLLLLLLLLLLLLLLLPPPPPPPPPPPPPPLLLLLLLLLLLLLLLLLRzJ_____
_______VtTNMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMNTtV_______
__________V_t_iSTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTSi_t_V__________
________________________________________________________________
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
}

@enduml